os:
- osx
language: node_js
node_js:
- node
script: npm run build
env:
  secure: "L8uLRt/gnSfbs34hlC57LP93gbtRNkp+YwGr6fmiADYCl3rQF8D5zzvig9oPXDnxXtW5QErTP7vzJdtdbkQ8s6UkAFpdAGQl/5YgB2aZB4Ya/4a/UdKnsKwgw74NmR8GadcmcXiipAi/L4tVC9ostP/Y/ESQRSGlMRl7elFkuQkEPO2GQuXr1z40tTEsfscY0/HiU6glwazX4NdLb4T77upFWJ+w3+2/NRzvEsWO11lGH3AD3Ne5ZVysfVvMICNh92ZjYovn7SKxcsEWHO7CKWqkJ7Oh4I1ac4e2yQNxQRf+jZmAJhECh4+Ye3OufF+6e5BJE+ug10F5xrXcBNnaha77bkH2RaxicyqMb8rMMXS9cJxbQs4TQPH4ZX43XGWIj6wFfJitqNL6h6Y5znX+ppfDAVvR/vL7W21VqLs7qQzMFNEr3Wlk7LKAqlkHAg++yV3YNvbY21xkDGoXTRnX5lJFpohLg9bwuWaJLqXdpvxOV4BNrcwX+AOCYVSI5jZlrbY7C90APv5xQnVhiIN8ZLHo4xW2lADahyB6oqZZKU7RtITuGLef/GYmAvl11BuvTektlG08JNjFsa4gyy1Sfetg1XnONlSOhUtJjKqCiLIkf0uAH9QdBoPbdOw42jUH8IL/5ONIZCu1+zY8FT9vJ7kYKq5tGK+PljSpaQOce4Q="
