os:
- osx
language: node_js
node_js:
- node
script: npm run build
env:
  secure: b7KBdHwwT1eFai59zKcihxz72lu+pE8hyEOFNLdGYdA548BIw56Y1UGddl9TGk9JZIfKuAYAmYMN6bW9zrYp5VZIYBc4P9RPhV8MNxoDGIUnxtNPrFo23hvH6/uw02KpERzKJIzPdsytNHAcCEXbzxlA4nBBtq8v5QkUtlLtTTfveOZDmOKrJolXufcZQgKw/OvanW43qUU+HSWNdNTWGfaX0VzEJKfmHBeEO/ZAGtYzPqvIU9g10FnI0mWuSzJG8vVxrxn4wXwEH03q9FMZwCwCTMaOw8V/Jc0k0z6D+xzHAgmbk5bCn97whzC50mkqjr+ylYGE3qxLEazb1CZd8hKP0qhrgN8TkP1GZu+AFUe54N24RwrfUqDllCsiT8Uz+gkwK80uqpithP0zxPz7dhYFSzzMRX56xJnIPm6JImrXG3hD8issJpdWu4pmuu9CegsznblhNVOn/A8o1NYBDJWW5caHNoKyaszaABu6sFtfNXNWok0/YZpzaeLhhHqB8Us7ndYQxf2cVPpgwEEZMKUHgAarUtGPGOslc/qRTsqvqUuQVkBWqZxVC/l8yX40QanBL31mYTLpfkze/rDwjCvWFF/J6UVvtEIllUvPzs6kkVOJEtR9Bfs14xdUwkKrx+UmD93avD+lbbM8oeMvXXK1QCCppqG6gigGvePbUYE=
